/*
 * InAddPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.in.ui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.ListUI;

import cn.hncu.bookStore.book.business.ebi.BookEbi;
import cn.hncu.bookStore.book.business.factory.BookEbiFactory;
import cn.hncu.bookStore.book.vo.BookModel;
import cn.hncu.bookStore.in.business.factory.InMainEbiFactory;
import cn.hncu.bookStore.in.vo.InDetailModel;
import cn.hncu.bookStore.in.vo.InMainModel;
import cn.hncu.bookStore.user.business.factory.UserEbiFactory;
import cn.hncu.bookStore.user.vo.UserModel;

/**
 * 
 * @author 陈浩翔
 * 
 * @version 1.0
 */
public class InAddPanel extends javax.swing.JPanel {

	private JFrame mainFrame = null;

	private List<InDetailModel> details = new ArrayList<InDetailModel>();

	/**
	 * Creates new form InAddPanel
	 * 
	 * @param mainFrame
	 */
	public InAddPanel(JFrame mainFrame) {
		this.mainFrame = mainFrame;
		initComponents();
		jtxArea.setEditable(false);
		myInitData();
	}

	private void myInitData() {
		// 1完成combBook组合框中数据的初始化
		// 访问book模块，把其中的图书获取出来，并把书名填写到combBook组合框中
		// 我们是UI层，只能访问(对方的)逻辑层
		List<BookModel> books = BookEbiFactory.getBookEbi().getAll();
		for (BookModel book : books) {
			combBook.addItem(book.getUuid() + "," + book.getName());
			// 若想更精确地控制每本书显示的信息，可以修改Book的toString()方法
		}

		// 2完成combUser组合框中数据的初始化
		/*
		 * 模块之间的交接太深(细节太多了，功能可实现，但从开发技术或设计思想来讲不可取) 
		  List<UserModel> users =UserEbiFactory.getUserEbi().getAll(); for(UserModel user: users){
		  if(user.getType()==UserTypeEnum.IN.getType()){
		  combUser.addItem(user.getName()); } }
		 */

		List<UserModel> users = UserEbiFactory.getUserEbi().getAllIn();
		for (UserModel user : users) {
			combUser.addItem(user.getName());
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		tfdInNum = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		combUser = new javax.swing.JComboBox();
		combBook = new javax.swing.JComboBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		jListDetails = new javax.swing.JList();
		jLabel7 = new javax.swing.JLabel();
		btnAddDetail = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jtxArea = new javax.swing.JTextArea();
		btnBack = new javax.swing.JButton();
		btnMainAdd = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 48));
		jLabel1.setForeground(new java.awt.Color(204, 0, 0));
		jLabel1.setText("\u6dfb\u52a0\u8fdb\u8d27");
		add(jLabel1);
		jLabel1.setBounds(270, 0, 210, 60);

		jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel4.setText("\u56fe\u4e66\u540d\u79f0:");
		add(jLabel4);
		jLabel4.setBounds(50, 100, 90, 30);

		tfdInNum.setFont(new java.awt.Font("Dialog", 1, 18));
		tfdInNum.setAutoscrolls(false);
		add(tfdInNum);
		tfdInNum.setBounds(140, 170, 150, 30);

		jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel5.setForeground(new java.awt.Color(255, 51, 51));
		jLabel5.setText("  \u8fdb\u8d27\u660e\u7ec6\u5217\u8868\uff1a");
		add(jLabel5);
		jLabel5.setBounds(10, 220, 140, 30);

		jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel6.setText("\u8fdb\u8d27\u4eba\uff1a");
		add(jLabel6);
		jLabel6.setBounds(480, 420, 80, 30);

		combUser.setFont(new java.awt.Font("Dialog", 1, 14));
		combUser.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "请选择..." }));
		add(combUser);
		combUser.setBounds(550, 420, 150, 30);

		combBook.setFont(new java.awt.Font("Dialog", 1, 14));
		combBook.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "请选择..." }));
		add(combBook);
		combBook.setBounds(140, 100, 150, 30);

		jListDetails.setFont(new java.awt.Font("Dialog", 1, 14));
		jListDetails.setForeground(new java.awt.Color(255, 51, 51));
		jListDetails.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jListDetails);

		add(jScrollPane1);
		jScrollPane1.setBounds(20, 262, 410, 210);

		jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel7.setText("\u8fdb\u8d27\u6570\u91cf\uff1a");
		add(jLabel7);
		jLabel7.setBounds(50, 170, 90, 30);

		btnAddDetail.setFont(new java.awt.Font("Dialog", 1, 14));
		btnAddDetail.setForeground(new java.awt.Color(0, 204, 204));
		btnAddDetail.setText("\u6dfb\u52a0\u5230\u660e\u7ec6");
		btnAddDetail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddDetailActionPerformed(evt);
			}
		});
		add(btnAddDetail);
		btnAddDetail.setBounds(480, 280, 120, 60);

		jtxArea.setColumns(20);
		jtxArea.setFont(new java.awt.Font("Dialog", 1, 14));
		jtxArea.setForeground(new java.awt.Color(0, 153, 51));
		jtxArea.setRows(5);
		jtxArea.setText("\u64cd\u4f5c\u8bf4\u660e\uff1a\n1\u3001\u9009\u62e9\u56fe\u4e66\u540d\u79f0\uff0c\u586b\u5199\u8fdb\u8d27\u6570\u91cf\u3002\n2\u3001\u518d\u70b9\u51fb\u4e0b\u65b9\u7684\u6dfb\u52a0\u5230\u660e\u7ec6\u6309\u94ae\uff0c\n      \u6dfb\u52a0\u6570\u636e\u5230\u8fdb\u8d27\u660e\u7ec6\u5217\u8868\uff0c\n      \u5982\u679c\u8fd8\u6709\u56fe\u4e66\uff0c\u91cd\u590d\u524d\u9762\u7684\u64cd\u4f5c\u3002\n3\u3001\u6700\u540e\u70b9\u51fb\u6dfb\u52a0\u6309\u94ae\u3002");
		jScrollPane2.setViewportView(jtxArea);

		add(jScrollPane2);
		jScrollPane2.setBounds(440, 100, 340, 140);

		btnBack.setFont(new java.awt.Font("Dialog", 1, 24));
		btnBack.setForeground(new java.awt.Color(0, 204, 204));
		btnBack.setText("\u8fd4\u56de");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});
		add(btnBack);
		btnBack.setBounds(520, 480, 120, 60);

		btnMainAdd.setFont(new java.awt.Font("Dialog", 1, 24));
		btnMainAdd.setForeground(new java.awt.Color(0, 204, 204));
		btnMainAdd.setText("\u6dfb\u52a0");
		btnMainAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnMainAddActionPerformed(evt);
			}
		});
		add(btnMainAdd);
		btnMainAdd.setBounds(120, 480, 120, 60);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnMainAddActionPerformed(java.awt.event.ActionEvent evt) {
		//1收集参数 
		String inUserName = combUser.getSelectedItem().toString();
		if (combUser.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(mainFrame, "请选择用户类型！");
			return;
		}
		//System.out.println(inUserName);

		String inUserUuid = UserEbiFactory.getUserEbi()
				.getUserByName(inUserName).getUuid();

		//2组织参数
		InMainModel inMain = new InMainModel();
		inMain.setInUserId(inUserUuid);
		inMain.setInUserName(inUserName);//设置：专为外键显示而补的数据

		//3调用逻辑层
		//System.out.println(inMain);
		//System.out.println(details);
		InMainEbiFactory.getInMainEbi().create(inMain, details);

		//4返回到结果页面
		mainFrame.setContentPane(new InListPanel(mainFrame));
		mainFrame.validate();

	}

	private void btnAddDetailActionPerformed(java.awt.event.ActionEvent evt) {
		//1收集参数
		String str = combBook.getSelectedItem().toString();

		//防范未选择图书
		if (combBook.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(mainFrame, "请选择图书！");
			return;
		}
		String strs[] = str.split(",");
		String bookUuid = strs[0];
		String bookName = strs[1];
		//		System.out.println(bookName);
		//		System.out.println(bookUuid);

		int sumNum = 0;
		try {
			sumNum = Integer.parseInt(tfdInNum.getText());
			if (sumNum < 0) {
				throw new NumberFormatException();
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(mainFrame, "进货数量格式错误！");
			return;
		}

		//2组织
		InDetailModel detail = new InDetailModel();
		detail.setBookId(bookUuid);
		detail.setSumNum(sumNum);
		//为显示给用户看，补的数据
		detail.setBookName(bookName);

		//3添加到List当中---真正的明细数据是details，界面上的只是回显信息
		details.add(detail);
		echoDetails();
	}

	private void echoDetails() {
		//处理进货人选择相同的书进货多次！这个操作是合并相同的书名的数量
		List<InDetailModel> lists = new ArrayList<InDetailModel>();
		for (InDetailModel model : details) {
			boolean isEqual = false;
			for (int i = 0; i < lists.size(); i++) {
				if (model.getBookName().equals(lists.get(i).getBookName())) {
					model.setSumNum(model.getSumNum()
							+ lists.get(i).getSumNum());
					lists.set(i, model);
					isEqual = true;
				}
			}
			if (!isEqual) {
				lists.add(model);
			}

		}
		details = lists;

		String echoStrs[] = new String[details.size()];

		for (int i = 0; i < details.size(); i++) {
			InDetailModel detail = details.get(i);
			echoStrs[i] = "《" + detail.getBookName() + "》,"
					+ detail.getSumNum() + "本";
		}
		jListDetails.setListData(echoStrs);
	}

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
		back();
	}

	private void back() {
		mainFrame.setContentPane(new InListPanel(mainFrame));
		mainFrame.validate();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnAddDetail;
	private javax.swing.JButton btnBack;
	private javax.swing.JButton btnMainAdd;
	private javax.swing.JComboBox combBook;
	private javax.swing.JComboBox combUser;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JList jListDetails;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jtxArea;
	private javax.swing.JTextField tfdInNum;
	// End of variables declaration//GEN-END:variables

}