/*
 * BookDeletePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.book.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import cn.hncu.bookStore.book.business.ebi.BookEbi;
import cn.hncu.bookStore.book.business.factory.BookEbiFactory;
import cn.hncu.bookStore.book.vo.BookModel;

/**
 * 
 * @author 陈浩翔
 *
 * @version 1.0
 */
public class BookDeletePanel extends javax.swing.JPanel {
	private JFrame mainFrame = null;
	private String uuid = null;

	/** Creates new form BookDeletePanel 
	 * @param mainFrame 
	 * @param uuid */
	public BookDeletePanel(JFrame mainFrame, String uuid) {
		this.mainFrame = mainFrame;
		this.uuid = uuid;
		initComponents();
		myInitData();
	}

	private void myInitData() {
		BookModel book = BookEbiFactory.getBookEbi().getSingle(uuid);
		//System.out.println(book);
		tfdName.setText(book.getName());
		tfdName.setEditable(false);

		tfdUuid.setText(book.getUuid());
		tfdUuid.setEditable(false);

		tfdInPrice.setText(String.valueOf(book.getInPrice()));
		tfdInPrice.setEditable(false);

		tfdSalePrice.setText(String.valueOf(book.getSalePrice()));
		tfdSalePrice.setEditable(false);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		tfdName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		tfdUuid = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		btnDelete = new javax.swing.JButton();
		btnBack = new javax.swing.JButton();
		tfdInPrice = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		tfdSalePrice = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 48));
		jLabel1.setForeground(new java.awt.Color(204, 0, 0));
		jLabel1.setText("\u5220\u9664\u56fe\u4e66");
		add(jLabel1);
		jLabel1.setBounds(280, 40, 230, 80);

		tfdName.setFont(new java.awt.Font("Dialog", 1, 18));
		tfdName.setAutoscrolls(false);
		add(tfdName);
		tfdName.setBounds(480, 190, 150, 30);

		jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel3.setText("uuid:");
		add(jLabel3);
		jLabel3.setBounds(130, 190, 50, 30);

		tfdUuid.setFont(new java.awt.Font("Dialog", 1, 12));
		add(tfdUuid);
		tfdUuid.setBounds(200, 190, 110, 30);

		jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel4.setText("\u56fe\u4e66\u540d\u79f0:");
		add(jLabel4);
		jLabel4.setBounds(380, 190, 90, 30);

		btnDelete.setFont(new java.awt.Font("Dialog", 1, 24));
		btnDelete.setForeground(new java.awt.Color(0, 204, 204));
		btnDelete.setText("\u5220\u9664");
		btnDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeleteActionPerformed(evt);
			}
		});
		add(btnDelete);
		btnDelete.setBounds(140, 440, 120, 60);

		btnBack.setFont(new java.awt.Font("Dialog", 1, 24));
		btnBack.setForeground(new java.awt.Color(0, 204, 204));
		btnBack.setText("\u8fd4\u56de");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});
		add(btnBack);
		btnBack.setBounds(520, 440, 120, 60);

		tfdInPrice.setFont(new java.awt.Font("Dialog", 1, 18));
		tfdInPrice.setAutoscrolls(false);
		add(tfdInPrice);
		tfdInPrice.setBounds(200, 300, 150, 30);

		jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel5.setText("\u8fdb\u8d27\u4ef7\u683c\uff1a");
		add(jLabel5);
		jLabel5.setBounds(100, 300, 90, 30);

		tfdSalePrice.setFont(new java.awt.Font("Dialog", 1, 18));
		tfdSalePrice.setAutoscrolls(false);
		add(tfdSalePrice);
		tfdSalePrice.setBounds(480, 300, 150, 30);

		jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel6.setText("\u552e\u8d27\u4ef7\u683c\uff1a");
		add(jLabel6);
		jLabel6.setBounds(380, 300, 90, 30);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
		back();
	}

	private void back() {
		mainFrame.setContentPane(new BookListPanel(mainFrame));
		mainFrame.validate();
	}

	private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
		//1收集参数
		//2组织参数
		//3调用逻辑层

		//4根据调用返回结果导向不同页面
		boolean isFlag = BookEbiFactory.getBookEbi().delete(uuid);
		if (isFlag) {
			back();
		} else {
			JOptionPane.showMessageDialog(null, "该图书已经不存在!");
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnBack;
	private javax.swing.JButton btnDelete;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField tfdInPrice;
	private javax.swing.JTextField tfdName;
	private javax.swing.JTextField tfdSalePrice;
	private javax.swing.JTextField tfdUuid;
	// End of variables declaration//GEN-END:variables

}