/*
 * BookAddPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.book.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import cn.hncu.bookStore.book.business.ebi.BookEbi;
import cn.hncu.bookStore.book.business.factory.BookEbiFactory;
import cn.hncu.bookStore.book.vo.BookModel;

/**
 * 
 * @author 陈浩翔
 *
 * @version 1.0
 */
public class BookAddPanel extends javax.swing.JPanel {
	private JFrame mainFrame = null;

	/** Creates new form BookAddPanel 
	 * @param mainFrame */
	public BookAddPanel(JFrame mainFrame) {
		this.mainFrame = mainFrame;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		tfdName = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		btnAdd = new javax.swing.JButton();
		btnBack = new javax.swing.JButton();
		tfdInPrice = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		tfdSalePrice = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 48));
		jLabel1.setForeground(new java.awt.Color(204, 0, 0));
		jLabel1.setText("\u6dfb\u52a0\u56fe\u4e66");
		add(jLabel1);
		jLabel1.setBounds(280, 40, 230, 80);

		tfdName.setFont(new java.awt.Font("Dialog", 1, 18));
		tfdName.setAutoscrolls(false);
		add(tfdName);
		tfdName.setBounds(280, 170, 150, 30);

		jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel4.setText("\u56fe\u4e66\u540d\u79f0:");
		add(jLabel4);
		jLabel4.setBounds(180, 170, 90, 30);

		btnAdd.setFont(new java.awt.Font("Dialog", 1, 24));
		btnAdd.setForeground(new java.awt.Color(0, 204, 204));
		btnAdd.setText("\u6dfb\u52a0");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});
		add(btnAdd);
		btnAdd.setBounds(140, 440, 120, 60);

		btnBack.setFont(new java.awt.Font("Dialog", 1, 24));
		btnBack.setForeground(new java.awt.Color(0, 204, 204));
		btnBack.setText("\u8fd4\u56de");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});
		add(btnBack);
		btnBack.setBounds(520, 440, 120, 60);

		tfdInPrice.setFont(new java.awt.Font("Dialog", 1, 18));
		tfdInPrice.setAutoscrolls(false);
		add(tfdInPrice);
		tfdInPrice.setBounds(280, 250, 150, 30);

		jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel5.setText("\u8fdb\u8d27\u4ef7\u683c\uff1a");
		add(jLabel5);
		jLabel5.setBounds(180, 250, 90, 30);

		tfdSalePrice.setFont(new java.awt.Font("Dialog", 1, 18));
		tfdSalePrice.setAutoscrolls(false);
		add(tfdSalePrice);
		tfdSalePrice.setBounds(280, 330, 150, 30);

		jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel6.setText("\u552e\u8d27\u4ef7\u683c\uff1a");
		add(jLabel6);
		jLabel6.setBounds(180, 330, 90, 30);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
		back();
	}

	private void back() {
		mainFrame.setContentPane(new BookListPanel(mainFrame));
		mainFrame.validate();
	}

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
		//1收集参数
		String name = tfdName.getText();
		double inPrice = 0;
		double salePrice = 0;
		try {
			inPrice = Double.parseDouble(tfdInPrice.getText());
			salePrice = Double.parseDouble(tfdSalePrice.getText());
		} catch (NumberFormatException e1) {
			JOptionPane.showMessageDialog(mainFrame, "价格的格式错误，请重新输入！");
			return;
		}


		if (name.equals("") || name.equals(null)) {
			JOptionPane.showMessageDialog(mainFrame, "用户名为空，请重新输入！");
			return;
		}

		//2组织参数
		BookModel book = new BookModel();
		book.setName(name);
		book.setInPrice(inPrice);
		book.setSalePrice(salePrice);

		//3调用逻辑层
		BookEbi ebi = BookEbiFactory.getBookEbi();

		//4根据调用返回结果导向不同页面
		if (ebi.create(book)) {
			back();
		} else {
			JOptionPane.showMessageDialog(null, "该图书已经存在!");
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnBack;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField tfdInPrice;
	private javax.swing.JTextField tfdName;
	private javax.swing.JTextField tfdSalePrice;
	// End of variables declaration//GEN-END:variables

}